### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by kairikibear** [nguyetn89/anomaly_ICCV2019#4]
Hi! Thanks for the hard work. I am currently trying to reimplement this code but what is still ambiguous to me is the following :
1. Preprocessing of the RGB frames
2. Preprocessing of the Flow frames

From load_images_and_flows, i saw some processing on the data loaded. It is save to assume that:
1. For the rgb frames, you divide them by 255, and afterwards you multiply by 2 and then substract 1 to get matrices with value within range of [-1, 1]
2. For the flow frames, you directly just use the flow outputted by flownet, the only extra processing is adding the magnitude channel

Thanks in advance!

**Comment by nguyetn89** [comment]
Hi @kairikibear,

Yes, the normalization of value range is explicitly performed only on RGB frames. In my opinion, the bounding range of optical flow is flexible (not strictly 0-255, 0-1 as RGB pixels), it is thus safer to keep their original values instead of normalizing them.

**Comment by kairikibear** [comment]
thank you!
