### ISSUE TITLE
some quesions in code

### ISSUE THREAD

**Issue by fangqian1234** [nguyetn89/anomaly_ICCV2019#7]
Hello, your code is very helpful to me. I am working in an urgent situation and need a complete code. It would be better if you could have the code of PyTorch framework.

**Comment by nguyetn89** [comment]
Hello, a PyTorch version of this model with some extensions is currently maintained (privately in the laboratory by my former colleagues). Unfortunately, it is expected to be published only after next several months (maybe summer or later).

**Comment by chowkamlee81** [comment]
@nguyetn89 
Do you have pytorch version of the code? Kindly help
